/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.villseriol.kakasi.jni;

public class kakasiJNI {
  public final static native void set_kanwadict(String jarg1);
  public final static native void set_itaijidict(String jarg1);
  public final static native long load_library(String jarg1);
  public final static native int kakasi_getopt_argv(long jarg1, String[] jarg2);
  public final static native String kakasi_do(long jarg1, byte[] jarg2);
  public final static native int kakasi_close(long jarg1);
}
