name: Publish Snapshot
on: [workflow_dispatch]
jobs:
  package-artifacts:
    uses: ./.github/workflows/package-artifacts.yml

  publish-snapshot:
    runs-on: ubuntu-latest
    needs: package-artifacts
    environment: staging
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: kakasi2-artifacts
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "11"
          server-id: central
          server-username: MAVEN_CENTRAL_USERNAME
          server-password: MAVEN_CENTRAL_PASSWORD
          gpg-private-key: ${{secrets.GPG_PRIVATE_KEY}}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Deploy to Maven Central
        env:
          MAVEN_CENTRAL_USERNAME: ${{secrets.MAVEN_CENTRAL_USERNAME}}
          MAVEN_CENTRAL_PASSWORD: ${{secrets.MAVEN_CENTRAL_PASSWORD}}
          MAVEN_GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
        run: |
          mvn gpg:sign-and-deploy-file \
            -DrepositoryId=maven \
            -Durl=${{ vars.MAVEN_REPOSITORY_URL }} \
            -Dfile=target/${{ needs.package-artifacts.outputs.snapshot_name }}.jar \
            -Dsources=target/${{ needs.package-artifacts.outputs.snapshot_name }}-sources.jar \
            -Djavadoc=target/${{ needs.package-artifacts.outputs.snapshot_name }}-javadoc.jar \
            -DpomFile=pom.xml
